### PR TITLE
Fix for our linear actuators not having accessible limit switches

### LINKED ISSUE #341: Rewrite all of our limit switch code to check for 0 duty cycle instead, because we can't access the limit switches
Apparently we can't access the limit switches in our linear actuators

### PR DESCRIPTION
**Pull request by Isopod00**

### CODE REVIEW

File: src/motor_control/src/motor_control_node.cpp [hunk 1]
```diff
@@ -374,6 +378,16 @@ class MotorControlNode : public rclcpp::Node {
   }
 
   void Potentiometer_callback(const rovr_interfaces::msg::Potentiometers msg) {
+    std_msgs::msg::Float32 digger_linear_actuator_msg;
+    digger_linear_actuator_msg.data = (this->can_data[this->get_parameter("DIGGER_LEFT_LINEAR_ACTUATOR").as_int()].dutyCycle + this->can_data[this->get_parameter("DIGGER_RIGHT_LINEAR_ACTUATOR").as_int()].dutyCycle)/2.0;
```
Comment (Isopod00) [inline src/motor_control/src/motor_control_node.cpp]: Instead of averaging the duty cycles of the two digging linear actuators, can you please publish both, and then in the digger subsystem logic you can check if either one == 0 and if either one does then we stop? Or if both ==0 then we stop, one of the two. To publish both, instead of using a Float32 publisher, try using a Float32[2] publisher to publish an array of Float32s of length 2.

File: src/motor_control/src/motor_control_node.cpp [hunk 2]
```diff
@@ -461,6 +482,8 @@ class MotorControlNode : public rclcpp::Node {
   }
 
   rclcpp::TimerBase::SharedPtr timer;
+  rclcpp::Publisher<std_msgs::msg::Float32>::SharedPtr digger_linear_actuator_pub;
```
Comment (Isopod00) [inline src/motor_control/src/motor_control_node.cpp]: try making this a Float32[2] publisher so you can publish both values

File: src/motor_control/src/motor_control_node.cpp [hunk 3]
```diff
@@ -385,6 +399,13 @@ class MotorControlNode : public rclcpp::Node {
       // Log an error message
       RCLCPP_ERROR(this->get_logger(), "ERROR: Position difference between linear actuators is too high! Stopping both motors.");
     }
+    else if ((this->can_data[this->get_parameter("DIGGER_LEFT_LINEAR_ACTUATOR").as_int()].dutyCycle > current_threshold) || (this->can_data[this->get_parameter("DIGGER_RIGHT_LINEAR_ACTUATOR").as_int()].dutyCycle > current_threshold)){
```
Comment (Isopod00) [inline src/motor_control/src/motor_control_node.cpp]: This current threshold code block you added doesn't really make sense now that we learned we don't have access to read the current draw, because current will spike when the motors need to work harder / fight against something but duty cycle will not, so it doesn't make sense to do this check with duty cycle. We should either remove this and forget about the check completely, or maybe we can try reading current from the motors again so we can actually use current, because this check only makes sense with current.

File: src/motor_control/src/motor_control_node.cpp [hunk 4]
```diff
@@ -308,6 +310,8 @@ class MotorControlNode : public rclcpp::Node {
     // Initialize timers below //
     timer = this->create_wall_timer(500ms, std::bind(&MotorControlNode::timer_callback, this));
 
+    digger_linear_actuator_pub = this->create_publisher<std_msgs::msg::Float32>("Digger Duty Cycle", 100);
```
Comment (Isopod00) [inline src/motor_control/src/motor_control_node.cpp]: try making this a Float32[2] publisher so you can publish both values

File: src/dumper/dumper/dumper_node.py [hunk 5]
```diff
@@ -62,19 +62,19 @@ def __init__(self):
 
         # Current state of the dumper
         self.extended_state = False
-        self.top_limit_pressed = False
-        self.bottom_limit_pressed = False
 
-        self.limit_switch_sub = self.create_subscription(LimitSwitches, "limitSwitches", self.limit_switch_callback, 10)
+        self.dumper_duty_cycle = 0.0
+
+        self.dumper_duty_cycle_sub = self.create_subscription(float, "dutyCycles", self.dumper_duty_cycle_callback, 10)
```
Comment (Isopod00) [inline src/dumper/dumper/dumper_node.py]: The topic name should be "Dumper Duty Cycle" because that is what you defined in the motor_control_node. Maybe change this to a name without spaces? you can use _ instead of spaces, which is a good convention.

File: src/digger/digger/digger_node.py [hunk 6]
```diff
@@ -64,7 +64,7 @@ def __init__(self):
         )
 
         # Define subscribers here
-        self.limit_switch_sub = self.create_subscription(LimitSwitches, "limitSwitches", self.limit_switch_callback, 10)
+        self.linear_actuator_duty_cycle_sub = self.create_subscription(float, "dutyCycles", self.linear_actuator_duty_cycle_callback, 10)
```
Comment (Isopod00) [inline src/digger/digger/digger_node.py]: The topic name should be "Digger Duty Cycle" because that is what you defined in the motor_control_node. Maybe change this to a name without spaces? you can use _ instead of spaces, which is a good convention.

File: src/digger/digger/digger_node.py [hunk 7]
```diff
@@ -88,9 +88,10 @@ def __init__(self):
         # Current state of the lift system
         self.lift_running = False
 
-        # Limit Switch States
-        self.top_limit_pressed = False
-        self.bottom_limit_pressed = False
+        # Lineaer Actuator Duty Cycles
+        self.linear_actuator_duty_cycle = 0.0
```
Comment (Isopod00) [inline src/digger/digger/digger_node.py]: Keep track of both duty cycles so we can check if either/both == 0.

File: src/digger/digger/digger_node.py [hunk 8]
```diff
@@ -148,12 +149,12 @@ def stop_lift(self) -> None:
     def lift_set_power(self, power: float) -> None:
         """This method sets power to the lift system."""
         self.lift_running = True
-        if power > 0 and self.top_limit_pressed:
```
Comment (Isopod00) [inline src/digger/digger/digger_node.py:151]: You can actually remove this safety check altogether because it isn't needed, the linear actuators will stop themselves from overextending with the built-in limit switches that we can't read.

File: src/digger/digger/digger_node.py [hunk 9]
```diff
@@ -148,12 +149,12 @@ def stop_lift(self) -> None:
...
-            self.get_logger().warn("WARNING: Top limit switch pressed!")
+        if power > 0 and self.linear_actuator_duty_cycle == 0.0:
+            self.get_logger().warn("WARNING: Duty Cycle is 0")
             self.stop_lift()  # Stop the lift system
             return
-        if power < 0 and self.bottom_limit_pressed:
```
Comment (Isopod00) [inline src/digger/digger/digger_node.py:155]: You can actually remove this safety check altogether because it isn't needed, the linear actuators will stop themselves from overextending with the built-in limit switches that we can't read.

File: src/digger/digger/digger_node.py [hunk 10]
```diff
@@ -259,14 +260,11 @@ def pot_callback(self, msg: Potentiometers):
...
-    def limit_switch_callback(self, limit_switches_msg):
-        """This subscriber callback method is called whenever a message is received on the limitSwitches topic."""
-        if not self.top_limit_pressed and limit_switches_msg.digger_top_limit_switch:
-            self.stop_lift()  # Stop the lift system
-        if not self.bottom_limit_pressed and limit_switches_msg.digger_bottom_limit_switch:
-            self.stop_lift()  # Stop the lift system
-        self.top_limit_pressed = limit_switches_msg.digger_top_limit_switch
-        self.bottom_limit_pressed = limit_switches_msg.digger_bottom_limit_switch
+    def linear_actuator_duty_cycle_callback(self, linear_acutator_msg):
+        if not self.linear_actuator_duty_cycle == 0.0 and linear_acutator_msg.data == 0.0:
```
Comment (Isopod00) [inline src/digger/digger/digger_node.py]: We don't need this part:

if not self.linear_actuator_duty_cycle == 0.0 and linear_acutator_msg.data == 0.0:
            self.stop_lift()
            
because if linear_acutator_msg.data == 0.0, that means the lift must already be stopped, no reason to tell it to stop again.

File: src/dumper/dumper/dumper_node.py [hunk 11]
```diff
@@ -62,19 +62,19 @@ def __init__(self):
...
 
     # Define subsystem methods here
     def set_power(self, dumper_power: float) -> None:
         """This method sets power to the dumper."""
-        if dumper_power > 0 and self.top_limit_pressed:
```
Comment (Isopod00) [inline src/dumper/dumper/dumper_node.py:73]: You can actually remove this safety check altogether because it isn't needed, the linear actuators will stop themselves from overextending with the built-in limit switches that we can't read.

File: src/dumper/dumper/dumper_node.py [hunk 12]
```diff
@@ -62,19 +62,19 @@ def __init__(self):
...
-            self.get_logger().warn("WARNING: Top limit switch pressed!")
+        if dumper_power > 0 and self.dumper_duty_cycle == 0.0:
+            self.get_logger().warn("WARNING: Duty cycle is 0.0!")
             self.stop()  # Stop the dumper
-        elif dumper_power < 0 and self.bottom_limit_pressed:
```
Comment (Isopod00) [inline src/dumper/dumper/dumper_node.py:76]: You can actually remove this safety check altogether because it isn't needed, the linear actuators will stop themselves from overextending with the built-in limit switches that we can't read.

File: src/dumper/dumper/dumper_node.py [hunk 13]
```diff
@@ -153,14 +153,10 @@ def retract_callback(self, request, response):
...
-    def limit_switch_callback(self, msg: LimitSwitches):
-        """This subscriber callback method is called whenever a message is received on the limitSwitches topic."""
-        if not self.top_limit_pressed and msg.dumper_top_limit_switch:
-            self.stop()  # Stop the lift system
-        if not self.bottom_limit_pressed and msg.dumper_bottom_limit_switch:
-            self.stop()  # Stop the lift system
-        self.top_limit_pressed = msg.dumper_top_limit_switch
-        self.bottom_limit_pressed = msg.dumper_bottom_limit_switch
+    def dumper_duty_cycle_callback(self, duty_cycle_msg):
+        if not self.dumper_duty_cycle == 0.0 and duty_cycle_msg.data == 0.0:
```
Comment (Isopod00) [inline src/dumper/dumper/dumper_node.py]: We don't need this part:

if not self.dumper_duty_cycle == 0.0 and duty_cycle_msg.data == 0.0:
self.stop()

because if duty_cycle_msg.data == 0.0, that means the dumper must already be stopped, no reason to tell it to stop again.

File: src/motor_control/src/motor_control_node.cpp [hunk 14]
```diff
@@ -61,6 +61,8 @@ struct DiggerLiftGoal {
   float value;
 };
 
+float current_threshold = 0.0; // TODO: Make this a ROS parameter like MAX_POS_DIFF is
```
Comment (Isopod00) [inline src/motor_control/src/motor_control_node.cpp]: You should remove this line since we ended up removing the max current draw check.

**Review by Isopod00 — COMMENTED** [review]
Some comments

File: src/motor_control/src/motor_control_node.cpp [hunk 15]
```diff
@@ -374,6 +379,16 @@ class MotorControlNode : public rclcpp::Node {
...
   void Potentiometer_callback(const rovr_interfaces::msg::Potentiometers msg) {
+    std_msgs::msg::Float32MultiArray digger_linear_actuator_msg;
+    digger_linear_actuator_msg.data = {this->can_data[this->get_parameter("DIGGER_LEFT_LINEAR_ACTUATOR").as_int()].dutyCycle, this->can_data[this->get_parameter("DIGGER_RIGHT_LINEAR_ACTUATOR").as_int()].dutyCycle};
+    digger_linear_actuator_pub->publish(digger_linear_actuator_msg);
+
+    std_msgs::msg::Float32 dumper_linear_actuator_msg;
+    dumper_linear_actuator_msg.data = this->can_data[this->get_parameter("DUMPER_MOTOR").as_int()].dutyCycle;
+    dumper_linear_actuator_pub->publish(dumper_linear_actuator_msg);
+
+
```
Comment (Isopod00) [inline src/motor_control/src/motor_control_node.cpp]: You have some extra empty lines here

File: src/digger/digger/digger_node.py [hunk 16]
```diff
@@ -88,9 +89,11 @@ def __init__(self):
...
         self.lift_running = False
 
-        # Limit Switch States
-        self.top_limit_pressed = False
-        self.bottom_limit_pressed = False
+        # Lineaer Actuator Duty Cycles
+        self.left_linear_actuator_duty_cycle = 0.0
+        self.right_linear_actuator_duty_cycle = 0.0
+        
+
```
Comment (Isopod00) [inline src/digger/digger/digger_node.py]: I think you have some extra empty lines here.

**Review by BergerKing333 — DISMISSED** [review]
look good to me

**Comment by Isopod00** [comment]
This looks good to me too! I say we merge it.
